sudo: required

language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sudo apt-get update -qq"
  - "sudo apt-get install python-tk python3-tk"  
script:
  - python checksum.py
  - python main.py
